In [6]:
import pandas as pd
from sqlalchemy import create_engine

In [7]:
# Conexao com o DB
engine = create_engine("sqlite:///ecommerce.db")

In [ ]:
# 1-> Total de vendas por categoria
consulta1 = "SELECT Categoria, SUM(Quantidade) AS Total_Qtd_Vendida FROM produtos GROUP BY Categoria"
resultado1 = pd.read_sql_query(consulta1, engine)
resultado1

    Categoria  Total_Qtd_Vendida
0  Acessórios                 81
1    Calçados                 46
2      Roupas                163

In [13]:
# 2-> Produto com mais vendas
consulta2 = "SELECT Produto, SUM(Quantidade) AS Total_Qtd_Vendida FROM produtos GROUP BY Produto ORDER BY Total_Qtd_Vendida DESC LIMIT 1"
resultado2 = pd.read_sql_query(consulta2, engine)
resultado2

    Produto  Total_Qtd_Vendida
0  Camiseta                 30

In [15]:
# 3 -> Total de vendas por produto
consulta3 = "SELECT Produto, SUM(Quantidade) AS Total_Qtd_Vendidos FROM produtos GROUP BY Produto ORDER BY Total_Qtd_Vendidos DESC"
resultado3 = pd.read_sql_query(consulta3, engine)
resultado3

       Produto  Total_Qtd_Vendidos
0     Camiseta                  30
1       Brinco                  30
2     Sandália                  25
3        Cinto                  22
4         Saia                  20
5       Shorts                  19
6      Bermuda                  18
7      Mochila                  15
8        Calça                  15
9        Blusa                  14
10     Vestido                  12
11  Saia longa                  11
12      Óculos                  10
13      Camisa                  10
14      Suéter                   9
15       Tênis                   8
16      Sapato                   7
17       Botas                   6
18     Jaqueta                   5
19     Relógio                   4

In [17]:
# 4-> Media de preco por categoria
consulta4 = "SELECT Categoria, AVG(Preço) AS Media_Preco_Categoria FROM produtos GROUP BY Categoria"
resultado4 = pd.read_sql_query(consulta4, engine)
resultado4

    Categoria  Media_Preco_Categoria
0  Acessórios             103.000000
1    Calçados             150.000000
2      Roupas              75.909091