In [12]:
import pandas as pd

In [13]:
dados = pd.read_json("../datasets/arquivosCSV/dadosProdutos.json", encoding="utf8")
dados

                                            produtos
0  {'id': 1, 'nome': 'Notebook Gamer', 'categoria...
1  {'id': 2, 'nome': 'Mouse Sem Fio', 'categoria'...
2  {'id': 3, 'nome': 'Teclado Mecânico', 'categor...
3  {'id': 4, 'nome': 'Monitor 27 Polegadas', 'cat...

In [16]:
# Filtro -> Produto mais caro
produto_mais_caro = max(dados['produtos'], key=lambda produto: produto['preco'])
produto_mais_caro

{'id': 1,
 'nome': 'Notebook Gamer',
 'categoria': 'Eletronicos',
 'preco': 4500.9,
 'estoque': 12,
 'avaliacao': 4.8,
 'fornecedor': {'nome': 'Dell', 'pais': 'Brasil'}}

In [17]:
# Normalizando meus dados
dataframe = pd.json_normalize(dados['produtos'])
dataframe

,id,nome,categoria,preco,estoque,avaliacao,fornecedor.nome,fornecedor.pais
0,1,Notebook Gamer,Eletronicos,4500.9,12,4.8,Dell,Brasil
1,2,Mouse Sem Fio,Perifericos,120.5,35,4.5,Logitech,Suica
2,3,Teclado Mecânico,Perifericos,350.0,20,4.7,Redragon,China
3,4,Monitor 27 Polegadas,Monitores,1500.0,8,4.9,Samsung,Coreia do Sul

In [21]:
# Filtro -> Produto mais bem avaliado
produto_melhor_avaliado = dataframe.loc[dataframe['avaliacao'].idxmax()].reset_index()
produto_melhor_avaliado

             index                     3
0               id                     4
1             nome  Monitor 27 Polegadas
2        categoria             Monitores
3            preco                1500.0
4          estoque                     8
5        avaliacao                   4.9
6  fornecedor.nome               Samsung
7  fornecedor.pais         Coreia do Sul

In [24]:
# Somando -> quantidade total em estoque
quantidade_estoque = sum(dataframe['estoque'])
quantidade_estoque

75