In [1]:
import pandas as pd

In [6]:
df_vendas = pd.DataFrame({
    'Produto': ['Notebook', 'Mouse', 'Notebook', 'Teclado', 'Mouse', 'Teclado'],
    'Quantidade': [2, 5, 1, 3, 2, 4],
    'Receita': [6000, 500, 3000, 900, 200, 1200],
    'Meses': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun']
})

df_vendas

    Produto  Quantidade  Receita Meses
0  Notebook           2     6000   Jan
1     Mouse           5      500   Fev
2  Notebook           1     3000   Mar
3   Teclado           3      900   Abr
4     Mouse           2      200   Mai
5   Teclado           4     1200   Jun

In [7]:
df_vendas_tratado = df_vendas.groupby('Produto')[['Quantidade', 'Receita']].sum().reset_index()
df_vendas_tratado

    Produto  Quantidade  Receita
0     Mouse           7      700
1  Notebook           3     9000
2   Teclado           7     2100

In [8]:
df_vendas_media = df_vendas.groupby('Produto')['Quantidade'].mean().reset_index()
df_vendas_media

    Produto  Quantidade
0     Mouse         3.5
1  Notebook         1.5
2   Teclado         3.5

In [18]:
produto_mais_vendido = df_vendas.groupby('Produto')['Quantidade'].sum().idxmax()
produto_mais_vendido

'Mouse'

In [20]:
maior_quantidade_vendida = df_vendas.groupby('Produto')['Receita'].sum().idxmax()
maior_quantidade_vendida

'Notebook'